package resto.tests;

import javax.swing.JOptionPane;
import resto.dao.RestaurantDAO;
import resto.entities.Restaurant;
import resto.tests.Menu;

public class InterfaceAffichageResto extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceAffichageResto
     */
   public static Restaurant r1= new Restaurant();
    private RestaurantDAO restDAO = new RestaurantDAO();
    public InterfaceAffichageResto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        modif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setName("Tab"); // NOI18N

        tab.setModel(new resto.tests.ModelTableResto());
        tab.setName("Tab");
        jScrollPane1.setViewportView(tab);

        ajouter.setText("Ajouter");
        ajouter.setName("Ajout"); // NOI18N
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.setName("Supprimer"); // NOI18N
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        modif.setText("Modifier");
        modif.setName("Modifier"); // NOI18N
        modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajouter)
                        .addGap(91, 91, 91)
                        .addComponent(supprimer)
                        .addGap(93, 93, 93)
                        .addComponent(modif)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(supprimer)
                    .addComponent(modif))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
       restDAO.deleteRestaurant(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 0).toString()));
       this.setVisible(false);
       new InterfaceAffichageResto().setVisible(true);
    }//GEN-LAST:event_supprimerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        this.setVisible(false);
        new InterfaceAjoutResto().setVisible(true);
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifActionPerformed
        r1.setId_resto_pk(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 0).toString())); 
        r1.setNom(tab.getValueAt(tab.getSelectedRow(), 1).toString());
        r1.setAdresse(tab.getValueAt(tab.getSelectedRow(), 2).toString());
        r1.setTheme(tab.getValueAt(tab.getSelectedRow(), 3).toString());
        r1.setSpecialite(tab.getValueAt(tab.getSelectedRow(), 4).toString());
        r1.setTel(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 5).toString()));
        r1.setBudget(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 6).toString()));
        r1.setAlcool(tab.getValueAt(tab.getSelectedRow(), 7).toString());
        r1.setId_menu_fk(Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 8).toString()));
        new InterfaceModifierResto().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAffichageResto().setVisible(true);
                
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modif;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
