/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Authentification.java
 *
 * Created on 25 févr. 2014, 17:12:09
 */

package resto.presentation;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import resto.dao.RestaurantDAO;
import resto.dao.authentificationDAO;
import resto.entities.Restaurant;
import resto.entities.authentification;

/**
 *
 * @author dali
 */
public class Authentification extends javax.swing.JFrame {
 RestaurantDAO dao = new RestaurantDAO();
    Restaurant res = new Restaurant();
    int a;
     public void setretrieveUserListener(ActionListener l) {
  retrieveUser.addActionListener(l);
 }

    /** Creates new form Authentification */
    public Authentification() {
        initComponents();
        Menu.setVisible(false);
        Gestionrestaurant.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Authentification = new javax.swing.JPanel();
        Login = new javax.swing.JTextField();
        connexion = new javax.swing.JButton();
        logintext = new javax.swing.JLabel();
        passwordtext = new javax.swing.JLabel();
        erreur = new javax.swing.JLabel();
        retrieveUser = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Deconnexion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Gestionrestaurant = new javax.swing.JPanel();
        et = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        theme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        specialite = new javax.swing.JTextField();
        alcool = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        annuler = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        budget = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        restorateur = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        et1 = new javax.swing.JLabel();
        et2 = new javax.swing.JLabel();
        et3 = new javax.swing.JLabel();
        et4 = new javax.swing.JLabel();
        et5 = new javax.swing.JLabel();
        et6 = new javax.swing.JLabel();
        et8 = new javax.swing.JLabel();
        et7 = new javax.swing.JLabel();
        et9 = new javax.swing.JLabel();
        et10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        modif1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        modif = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Deconnexion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Authentification.setBackground(new java.awt.Color(255, 255, 255));
        Authentification.setToolTipText("");

        connexion.setBackground(new java.awt.Color(204, 255, 204));
        connexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/key.png"))); // NOI18N
        connexion.setText("Connexion");
        connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionActionPerformed(evt);
            }
        });

        logintext.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logintext.setText("Login:");

        passwordtext.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        passwordtext.setText("Password:");

        erreur.setForeground(new java.awt.Color(255, 0, 51));

        retrieveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/fac.png"))); // NOI18N
        retrieveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveUserActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout AuthentificationLayout = new javax.swing.GroupLayout(Authentification);
        Authentification.setLayout(AuthentificationLayout);
        AuthentificationLayout.setHorizontalGroup(
            AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AuthentificationLayout.createSequentialGroup()
                                .addComponent(logintext)
                                .addGap(31, 31, 31))
                            .addGroup(AuthentificationLayout.createSequentialGroup()
                                .addComponent(passwordtext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password)
                            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addComponent(retrieveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(AuthentificationLayout.createSequentialGroup()
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(erreur)))
                .addContainerGap(1020, Short.MAX_VALUE))
        );
        AuthentificationLayout.setVerticalGroup(
            AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthentificationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erreur)
                .addGap(8, 8, 8)
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logintext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordtext)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retrieveUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GESTION DES CLIENT");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GESTION DES RESTAURATEUR");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/28911_70031_food_grey_restaurant.png"))); // NOI18N
        jButton3.setText("GESTION DES RESTAURANT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/e-mail.png"))); // NOI18N
        jButton4.setText("MAIL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/commentaires.png"))); // NOI18N
        jButton5.setText("GESTION  DES COMMENTAIRES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("STATISTIQUE");

        Deconnexion.setBackground(new java.awt.Color(255, 255, 255));
        Deconnexion.setText("Deconnexion");
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Deconnexion)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(124, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deconnexion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Gestionrestaurant.setBackground(new java.awt.Color(255, 255, 255));
        Gestionrestaurant.setForeground(new java.awt.Color(255, 255, 255));

        et.setBackground(new java.awt.Color(255, 255, 255));
        et.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N
        et.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Numero du menu");

        nom.setName("nom"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Budget");

        theme.setName("theme"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Alcool");

        adresse.setName("addresse"); // NOI18N

        tel.setName("telephone"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Spécialite");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Telephone");

        specialite.setName("specialite"); // NOI18N

        alcool.setName("alchool"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Adresse");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Théme");

        menu.setName("menu"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("Nom");

        annuler.setBackground(new java.awt.Color(255, 255, 255));
        annuler.setText("   Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        ajouter.setBackground(new java.awt.Color(255, 255, 255));
        ajouter.setText(" Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Num restaurateur");

        restorateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restorateurActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("E-mail");

        et1.setBackground(new java.awt.Color(255, 255, 255));
        et1.setForeground(new java.awt.Color(255, 255, 255));
        et1.setText("*");

        et2.setForeground(new java.awt.Color(255, 255, 255));
        et2.setText("*");

        et3.setForeground(new java.awt.Color(255, 255, 255));
        et3.setText("*");

        et4.setForeground(new java.awt.Color(255, 255, 255));
        et4.setText("*");

        et5.setForeground(new java.awt.Color(255, 255, 255));
        et5.setText("*");

        et6.setForeground(new java.awt.Color(255, 255, 255));
        et6.setText("*");

        et8.setForeground(new java.awt.Color(255, 255, 255));
        et8.setText("*");

        et7.setForeground(new java.awt.Color(255, 255, 255));
        et7.setText("*");

        et9.setForeground(new java.awt.Color(255, 255, 255));
        et9.setText("*");

        et10.setForeground(new java.awt.Color(255, 255, 255));
        et10.setText("*");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*");

        titre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titre.setText("Ajouter un restaurant");

        modif1.setBackground(new java.awt.Color(255, 255, 255));
        modif1.setText("Modifier");
        modif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modif1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout etLayout = new javax.swing.GroupLayout(et);
        et.setLayout(etLayout);
        etLayout.setHorizontalGroup(
            etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etLayout.createSequentialGroup()
                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(etLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(etLayout.createSequentialGroup()
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(etLayout.createSequentialGroup()
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8))
                                .addGap(37, 37, 37)
                                .addComponent(et10)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(restorateur, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(menu)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etLayout.createSequentialGroup()
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(etLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(et6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(et5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(budget)))
                            .addGroup(etLayout.createSequentialGroup()
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(etLayout.createSequentialGroup()
                                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(et4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(et3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(et2, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(et1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                    .addComponent(adresse, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(theme, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(specialite, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(et9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(etLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(et7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(et8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alcool, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(etLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titre)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modif1)
                        .addGap(18, 18, 18)
                        .addComponent(annuler)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter)))
                .addContainerGap())
        );
        etLayout.setVerticalGroup(
            etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etLayout.createSequentialGroup()
                .addComponent(titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etLayout.createSequentialGroup()
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(et1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(et2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(et3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(et4)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(et5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(et6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(et7))
                        .addGap(12, 12, 12)
                        .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(et8)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(et9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(restorateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(et10)
                    .addComponent(jLabel13))
                .addGap(49, 49, 49)
                .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modif1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des restaurants", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        supprimer.setBackground(new java.awt.Color(255, 255, 255));
        supprimer.setText("   Supprimer");
        supprimer.setActionCommand("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        tab.setModel(new ModelTable());
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        modif.setBackground(new java.awt.Color(255, 255, 255));
        modif.setText("Modifier");
        modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(modif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Recherche :");

        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });
        recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercheKeyReleased(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/images/trouver-recherche-zoom-icone-4884-32.png"))); // NOI18N

        Deconnexion1.setBackground(new java.awt.Color(255, 255, 255));
        Deconnexion1.setText("Deconnexion");
        Deconnexion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deconnexion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GestionrestaurantLayout = new javax.swing.GroupLayout(Gestionrestaurant);
        Gestionrestaurant.setLayout(GestionrestaurantLayout);
        GestionrestaurantLayout.setHorizontalGroup(
            GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionrestaurantLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Deconnexion1)
                    .addGroup(GestionrestaurantLayout.createSequentialGroup()
                        .addComponent(et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GestionrestaurantLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GestionrestaurantLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        GestionrestaurantLayout.setVerticalGroup(
            GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionrestaurantLayout.createSequentialGroup()
                .addGroup(GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestionrestaurantLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GestionrestaurantLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Deconnexion1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GestionrestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authentification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gestionrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authentification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(101, 101, 101)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(Gestionrestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retrieveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrieveUserActionPerformed

    private void connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionActionPerformed
    String log;
    String pwd;
    log=Login.getText();
    pwd=Password.getText();
    authentification aut=new authentification();
    authentification autdb=new authentification();
    aut.setLogin(log);
    aut.setPassword(pwd);
    authentificationDAO autdao=new authentificationDAO();
    autdb=autdao.verifier(log);
    if(aut.equals(autdb))
    {
        Gestionrestaurant.setVisible(false);
        Authentification.setVisible(false);
        Menu.setVisible(true);
        
    }
    else{
        erreur.setText("Login or Password is Incorrect");
    }
    
    }//GEN-LAST:event_connexionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
       // new InboxFrame().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
        Menu.setVisible(false);
        Authentification.setVisible(true);
    }//GEN-LAST:event_DeconnexionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      Menu.setVisible(false);
      Authentification.setVisible(false);
      Gestionrestaurant.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Deconnexion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deconnexion1ActionPerformed
        Menu.setVisible(false);
        Authentification.setVisible(true);
    }//GEN-LAST:event_Deconnexion1ActionPerformed

    private void rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheKeyReleased
        List<Restaurant> li = new RestaurantDAO().RechercherAllResto(recherche.getText());
        ModelTable model1 = new ModelTable(li);
        tab.setModel(model1);
    }//GEN-LAST:event_rechercheKeyReleased

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
        int userId = Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 0).toString());
        // this.setVisible(false);
        //new GestionRestaurant().setVisible(true);
    }//GEN-LAST:event_rechercheActionPerformed

    private void modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifActionPerformed
        if(tab.getSelectedRow()!=-1){
            Restaurant R=new Restaurant();
            RestaurantDAO rdao=new RestaurantDAO();
            R= rdao.findRestoByID((Integer) tab.getValueAt(tab.getSelectedRow(), 0));
            a=(Integer) tab.getValueAt(tab.getSelectedRow(), 0);

            titre.setText("Modifier restaurateur");
            modif1.setVisible(true);
            ajouter.setVisible(false);

            nom.setText(R.getNom());
            adresse.setText(R.getAdresse());
            theme.setText(R.getTheme());
            specialite.setText(R.getSpecialite());
            tel.setText(Integer.toString(R.getTel()));
            budget.setText(Integer.toString(R.getBudget()));
            alcool.setText(R.getAlcool());
            menu.setText(Integer.toString(R.getId_menu_fk()));
            restorateur.setText(Integer.toString(R.getId_restaurateur_fk()));
            mail.setText(R.getMail());

            System.out.println(R);
            //this.setVisible(true);

        }else
        {
            int d=JOptionPane.OK_CANCEL_OPTION;
            JOptionPane.showConfirmDialog(null, "Vous n'avez pas sélectionnez un restaurateur","erreur",d);

        }
    }//GEN-LAST:event_modifActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked

    }//GEN-LAST:event_tabMouseClicked

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Voulez vous supprimer les Clients selectionnés?", "Warning", dialogButton);

        if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here

            RestaurantDAO restDAO = new RestaurantDAO();

            int userId = Integer.parseInt(tab.getValueAt(tab.getSelectedRow(), 0).toString());
            restDAO.deleteRestaurant(userId);

            ModelTable model = new ModelTable();
            tab.setModel(model);
        }
        //this.setVisible(false);
        //new GestionRestaurant().setVisible(true);
    }//GEN-LAST:event_supprimerActionPerformed

    private void modif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modif1ActionPerformed
        String masque = "^[a-zA-Z]+[a-zA-Z0-9\\._-]*[a-zA-Z0-9]@[a-zA-Z]+"+ "[a-zA-Z0-9\\._-]*[a-zA-Z0-9]+\\.[a-zA-Z]{2,4}$";
        Pattern pattern = Pattern.compile(masque);
        Matcher controler = pattern.matcher(mail.getText());
        int b=0;
        int c=0;
        int d=0;
        int e =0;
        int f=0;
        int g=0;
        int h=0;
        int i=0;
        int j=0;
        try
        {
            j = Integer.parseInt(alcool.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            i = Integer.parseInt(specialite.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            h = Integer.parseInt(theme.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            g = Integer.parseInt(adresse.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            f = Integer.parseInt(nom.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            e = Integer.parseInt(restorateur.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            d = Integer.parseInt(menu.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            c = Integer.parseInt(budget.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            b = Integer.parseInt(tel.getText());

        }
        catch (NumberFormatException ex)
        {
        }

        if(nom.getText().equals("") ==false && f==0 && adresse.getText().equals("") ==false && g==0 && theme.getText().equals("") == false && h==0 && specialite.getText().equals("") == false && i==0 && tel.getText().equals("") ==false && b!=0 && budget.getText().equals("") ==false && c!=0 && alcool.getText().equals("") == false && j==0 && menu.getText().equals("") ==false && d!=0 && restorateur.getText().equals("") == false && e!=0 && controler.matches()==true)
        {

            res.setId_resto_pk(a);
            res.setNom(nom.getText());
            res.setAdresse(adresse.getText());
            res.setTheme(theme.getText());
            res.setSpecialite(specialite.getText());
            res.setTel(Integer.parseInt(tel.getText()));
            res.setBudget(Integer.parseInt(budget.getText()));
            res.setAlcool(alcool.getText());
            res.setId_menu_fk(Integer.parseInt(menu.getText()));
            res.setId_restaurateur_fk(Integer.parseInt(restorateur.getText()));
            res.setMail(mail.getText());

            dao.updateRestaurant(res);
            titre.setText("Ajouter restaurant");
            modif1.setVisible(false);
            ajouter.setVisible(true);

            JOptionPane.showConfirmDialog(this, "confirmation");
            //System.out.println(res);
            this.annulerActionPerformed(evt);

            tab.setModel(new ModelTable());
            //this.setVisible(false);
            //new GestionRestaurant().setVisible(true);
        }
        else
        {
            if(nom.getText().equals("") ==true || f!=0)
            {
                et1.setForeground(Color.red);
                //nom.setBackground(Color.red);
            }
            if(adresse.getText().equals("") ==true || g!=0)
            {
                et2.setForeground(Color.red);
                //adresse.setBackground(Color.red);
            }
            if(theme.getText().equals("") ==true || h!=0)
            {
                et3.setForeground(Color.red);
                //theme.setBackground(Color.red);
            }
            if(specialite.getText().equals("") ==true || i!=0)
            {
                et4.setForeground(Color.red);
                //specialite.setBackground(Color.red);
            }
            if(tel.getText().equals("") ==true || b==0)
            {
                et5.setForeground(Color.red);
                //tel.setBackground(Color.red);
            }

            if(budget.getText().equals("") ==true || c==0)
            {
                et6.setForeground(Color.red);
                //budget.setBackground(Color.red);
            }

            if(alcool.getText().equals("") ==true || j!=0)
            {
                et7.setForeground(Color.red);
                //alcool.setBackground(Color.red);
            }
            if(menu.getText().equals("") ==true || d==0)
            {
                et9.setForeground(Color.red);
                //menu.setBackground(Color.red);
            }
            if(restorateur.getText().equals("") ==true || e==0)
            {
                jLabel9.setForeground(Color.red);
                //restorateur.setBackground(Color.red);
            }
            if(controler.matches()!=true)
            {
                et8.setForeground(Color.red);
                //mail.setBackground(Color.red);
            }

        }
    }//GEN-LAST:event_modif1ActionPerformed

    private void restorateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restorateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restorateurActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        String masque = "^[a-zA-Z]+[a-zA-Z0-9\\._-]*[a-zA-Z0-9]@[a-zA-Z]+"+ "[a-zA-Z0-9\\._-]*[a-zA-Z0-9]+\\.[a-zA-Z]{2,4}$";
        Pattern pattern = Pattern.compile(masque);
        Matcher controler = pattern.matcher(mail.getText());
        int b=0;
        int c=0;
        int d=0;
        int e =0;
        int f=0;
        int g=0;
        int h=0;
        int i=0;
        int j=0;
        try
        {
            j = Integer.parseInt(alcool.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            i = Integer.parseInt(specialite.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            h = Integer.parseInt(theme.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            g = Integer.parseInt(adresse.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            f = Integer.parseInt(nom.getText());

        }
        catch (NumberFormatException ex)
        {

        }
        try
        {
            e = Integer.parseInt(restorateur.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            d = Integer.parseInt(menu.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            c = Integer.parseInt(budget.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        try
        {
            b = Integer.parseInt(tel.getText());

        }
        catch (NumberFormatException ex)
        {
        }
        if(nom.getText().equals("") ==false && f==0 && adresse.getText().equals("") ==false && g==0 && theme.getText().equals("") == false && h==0 && specialite.getText().equals("") == false && i==0 && tel.getText().equals("") ==false && b!=0 && budget.getText().equals("") ==false && c!=0 && alcool.getText().equals("") == false && j==0 && menu.getText().equals("") ==false && d!=0 && restorateur.getText().equals("") == false && e!=0 && controler.matches()==true)
        {
            res = new Restaurant(nom.getText(), adresse.getText(), theme.getText(), specialite.getText(),Integer.parseInt(tel.getText()),Integer.parseInt(budget.getText()),alcool.getText(), Integer.parseInt(menu.getText()), Integer.parseInt(restorateur.getText()),mail.getText());
            dao.insertRestaurant(res);
            this.annulerActionPerformed(evt);

            tab.setModel(new ModelTable());
            //this.setVisible(false);
            //new GestionRestaurant().setVisible(true);
        }
        else
        {
            if(nom.getText().equals("") ==true || f!=0)
            {
                et1.setForeground(Color.red);
                //nom.setBackground(Color.red);
            }
            if(adresse.getText().equals("") ==true || g!=0)
            {
                et2.setForeground(Color.red);
                //adresse.setBackground(Color.red);
            }
            if(theme.getText().equals("") ==true || h!=0)
            {
                et3.setForeground(Color.red);
                //theme.setBackground(Color.red);
            }
            if(specialite.getText().equals("") ==true || i!=0)
            {
                et4.setForeground(Color.red);
                //specialite.setBackground(Color.red);
            }
            if(tel.getText().equals("") ==true || b==0)
            {
                et5.setForeground(Color.red);
                //tel.setBackground(Color.red);
            }

            if(budget.getText().equals("") ==true || c==0)
            {
                et6.setForeground(Color.red);
                //budget.setBackground(Color.red);
            }

            if(alcool.getText().equals("") ==true || j!=0)
            {
                et7.setForeground(Color.red);
                //alcool.setBackground(Color.red);
            }
            if(menu.getText().equals("") ==true || d==0)
            {
                et9.setForeground(Color.red);
                //menu.setBackground(Color.red);
            }
            if(restorateur.getText().equals("") ==true || e==0)
            {
                jLabel9.setForeground(Color.red);
                //restorateur.setBackground(Color.red);
            }
            if(controler.matches()!=true)
            {
                et8.setForeground(Color.red);
                //mail.setBackground(Color.red);
            }

        }
    }//GEN-LAST:event_ajouterActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        nom.setText("");
        adresse.setText("");
        specialite.setText("");
        theme.setText("");
        tel.setText("");
        budget.setText("");
        alcool.setText("");
        menu.setText("");
        restorateur.setText("");
        mail.setText("");
        //this.setVisible(false);
        //new GestionRestaurant().setVisible(true);
    }//GEN-LAST:event_annulerActionPerformed

    /**
    * @param args the command line arguments
    */
  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
           
            public void run() {
                new Authentification().setVisible(true);
               
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Authentification;
    private javax.swing.JButton Deconnexion;
    private javax.swing.JButton Deconnexion1;
    private javax.swing.JPanel Gestionrestaurant;
    private javax.swing.JTextField Login;
    private javax.swing.JPanel Menu;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField adresse;
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField alcool;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField budget;
    private javax.swing.JButton connexion;
    private javax.swing.JLabel erreur;
    private javax.swing.JPanel et;
    private javax.swing.JLabel et1;
    private javax.swing.JLabel et10;
    private javax.swing.JLabel et2;
    private javax.swing.JLabel et3;
    private javax.swing.JLabel et4;
    private javax.swing.JLabel et5;
    private javax.swing.JLabel et6;
    private javax.swing.JLabel et7;
    private javax.swing.JLabel et8;
    private javax.swing.JLabel et9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logintext;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField menu;
    private javax.swing.JButton modif;
    private javax.swing.JButton modif1;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel passwordtext;
    private javax.swing.JTextField recherche;
    private javax.swing.JTextField restorateur;
    private javax.swing.JButton retrieveUser;
    private javax.swing.JTextField specialite;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField theme;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables

}
