/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.presentation;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import resto.entities.Restaurateur;
import resto.dao.RestaurateurDAO;
import javax.swing.JTable;
import resto.dao.authentificationDAO;
import resto.entities.authentification;

/**
 *
 * @author fares
 */
public class Liste_restaurateur extends javax.swing.JFrame {
//       int b;
//       RestaurateurDAO resDAO = new RestaurateurDAO();

    /**
     * Creates new form Liste_restaurateur
     */
    private int t;
    private  int y;
    public Liste_restaurateur() {

        initComponents();
        btn_Vmodif.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Gestionrestaurateur = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLste = new javax.swing.JTable();
        btnSupp = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RbHomme = new javax.swing.JRadioButton();
        RbFemme = new javax.swing.JRadioButton();
        btn_valider = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        jlabel15 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        btn_Vmodif = new javax.swing.JButton();
        btn_Annuler = new javax.swing.JButton();
        et1 = new javax.swing.JLabel();
        et2 = new javax.swing.JLabel();
        et3 = new javax.swing.JLabel();
        et4 = new javax.swing.JLabel();
        et5 = new javax.swing.JLabel();
        et6 = new javax.swing.JLabel();
        et7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cPassword = new javax.swing.JPasswordField();
        et8 = new javax.swing.JLabel();
        CLogin = new javax.swing.JTextField();
        CNom = new javax.swing.JTextField();
        CPrenom = new javax.swing.JTextField();
        CDateN = new javax.swing.JTextField();
        Ctel = new javax.swing.JTextField();
        CAdresse1 = new javax.swing.JTextField();
        Ccin = new javax.swing.JTextField();
        CMail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        Gestionrestaurateur.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste restaurateur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 24))); // NOI18N

        tbLste.setModel(new ModelTableRestaurateurs()
        );
        jScrollPane1.setViewportView(tbLste);

        btnSupp.setBackground(new java.awt.Color(255, 255, 255));
        btnSupp.setText("Supprimer");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        btnUp.setBackground(new java.awt.Color(255, 255, 255));
        btnUp.setText("Modifier");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(373, 373, 373))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Nom:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Prénom:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Date naissance:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Téléphone:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Adresse:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Sexe:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Cin:");

        buttonGroup1.add(RbHomme);
        RbHomme.setText("Homme");
        RbHomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbHommeActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbFemme);
        RbFemme.setText("Femme");

        btn_valider.setBackground(new java.awt.Color(255, 255, 255));
        btn_valider.setText("Ajouter");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(255, 255, 255));
        btn_Reset.setActionCommand("jButton1");
        btn_Reset.setLabel("Reinialisation");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        jlabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlabel15.setText("Mail");

        title.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        title.setText("Ajouter restaurateur");

        btn_Vmodif.setBackground(new java.awt.Color(255, 255, 255));
        btn_Vmodif.setText("Modifier");
        btn_Vmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VmodifActionPerformed(evt);
            }
        });

        btn_Annuler.setBackground(new java.awt.Color(255, 255, 255));
        btn_Annuler.setText("Annuler");
        btn_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnnulerActionPerformed(evt);
            }
        });

        et1.setBackground(new java.awt.Color(255, 255, 255));
        et1.setForeground(new java.awt.Color(255, 255, 255));
        et1.setText("*");

        et2.setForeground(new java.awt.Color(255, 255, 255));
        et2.setText("*");

        et3.setForeground(new java.awt.Color(255, 255, 255));
        et3.setText("*");

        et4.setForeground(new java.awt.Color(255, 255, 255));
        et4.setText("*");

        et5.setForeground(new java.awt.Color(255, 255, 255));
        et5.setText("*");

        et6.setForeground(new java.awt.Color(255, 255, 255));
        et6.setText("*");

        et7.setForeground(new java.awt.Color(255, 255, 255));
        et7.setText("*");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Login:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Mot de passe:");

        et8.setBackground(new java.awt.Color(255, 255, 255));
        et8.setForeground(new java.awt.Color(255, 255, 255));
        et8.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(et8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(et4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(et5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlabel15)
                                    .addComponent(jLabel7))
                                .addGap(117, 117, 117)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ccin, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(et6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(401, 401, 401))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(78, 78, 78)
                                .addComponent(CPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(CDateN, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(RbHomme)
                                            .addGap(33, 33, 33)
                                            .addComponent(RbFemme))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CAdresse1)
                                            .addComponent(Ctel)
                                            .addComponent(cPassword))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(et2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(279, 279, 279))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(631, 631, 631)
                                .addComponent(et3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_Vmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_valider)
                                        .addGap(3, 3, 3)
                                        .addComponent(btn_Reset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Annuler))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(83, 83, 83)
                                .addComponent(et1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CNom, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(et7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(et1)
                        .addComponent(CNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(et2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(CPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et3)
                    .addComponent(jLabel3)
                    .addComponent(CDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Ctel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CAdresse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(et4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(et7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(et5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RbFemme)
                            .addComponent(RbHomme))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et6)
                            .addComponent(jLabel7)
                            .addComponent(Ccin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(et8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Vmodif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout GestionrestaurateurLayout = new javax.swing.GroupLayout(Gestionrestaurateur);
        Gestionrestaurateur.setLayout(GestionrestaurateurLayout);
        GestionrestaurateurLayout.setHorizontalGroup(
            GestionrestaurateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestionrestaurateurLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GestionrestaurateurLayout.setVerticalGroup(
            GestionrestaurateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestionrestaurateurLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(GestionrestaurateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Gestionrestaurateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gestionrestaurateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(ActionEvent e) {

    }
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        ModelTableRestaurateurs Model = new ModelTableRestaurateurs();
        tbLste.setModel(Model);
        Model.fireTableDataChanged();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btn_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnnulerActionPerformed
        CNom.setText("");
        CPrenom.setText("");
        CDateN.setText("");
        Ctel.setText("");
        CLogin.setText("");
        Ccin.setText("");
        CMail.setText("");
        title.setText("Ajouter restaurateur");
    }//GEN-LAST:event_btn_AnnulerActionPerformed

    private void btn_VmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VmodifActionPerformed
        String masque = "^[a-zA-Z]+[a-zA-Z0-9\\._-]*[a-zA-Z0-9]@[a-zA-Z]+" + "[a-zA-Z0-9\\._-]*[a-zA-Z0-9]+\\.[a-zA-Z]{2,4}$";
        Pattern pattern = Pattern.compile(masque);
        Matcher controler = pattern.matcher(CMail.getText());
        int j = 0;
        int a = 0;
        int b = 0;
        int c = 0;
        int d = 0;
        int e = 0;
        int f = 0;
        int g = 0;

        try {
            j = Integer.parseInt(CNom.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            a = Integer.parseInt(CPrenom.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            b = Integer.parseInt(CDateN.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            c = Integer.parseInt(Ctel.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            d = Integer.parseInt(CAdresse1.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            g= Integer.parseInt(CLogin.getText());

        } catch (NumberFormatException ex) {
        }

        try {
            e = Integer.parseInt(Ccin.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            f = Integer.parseInt(CMail.getText());

        } catch (NumberFormatException ex) {
        }

        String test = CLogin.getText();
        authentificationDAO aut;
        aut = new authentificationDAO();
        authentification azerty = aut.verifierR(test);

        if (CNom.getText().equals("") == false && j == 0 && CPrenom.getText().equals("") == false && a == 0 && CDateN.getText().equals("") == false && b == 0 && Ctel.getText().equals("") == false && c != 0 && CAdresse1.getText().equals("") == false && d == 0 && Ccin.getText().equals("") == false && e != 0 && controler.matches() == true && g==0 && CLogin.getText().equals(azerty.getLogin())==false )
        {
            String resu = " ";
            if (RbHomme.isSelected()) {
                resu = RbHomme.getText();
            }
            if (RbFemme.isSelected()) {
                resu = RbFemme.getText();
            }

            RestaurateurDAO resDAO = new RestaurateurDAO();
            Restaurateur rest = new Restaurateur();
            authentification auth = new authentification();
            auth.setLogin(CLogin.getText());
            auth.setPassword(cPassword.getText());

            rest.setId_restaurateur_pk(t);
            rest.setNom(CNom.getText());
            rest.setPrenom(CPrenom.getText());
            rest.setDate_naissance(CDateN.getText());
            rest.setTel(Integer.parseInt(Ctel.getText()));
            rest.setAdresse(CAdresse1.getText());
            rest.setSexe(resu);
            rest.setCin(Integer.parseInt(Ccin.getText()));
            rest.setMail(CMail.getText());
            //System.out.println(rest.getMail());
            auth.setId(y);
            auth.setId_utilisateur(t);
            JOptionPane.showConfirmDialog(this, "Voulez vous confirmer les modifications?");
            System.out.println(rest);
            resDAO.updateRestaurateur(rest,auth);
        } else {
            if (CNom.getText().equals("") == true || j != 0) {
                et1.setForeground(Color.red);
                //nom.setBackground(Color.red);
            }
            if (CPrenom.getText().equals("") == true || a != 0) {
                et2.setForeground(Color.red);
                //adresse.setBackground(Color.red);
            }
            if (CDateN.getText().equals("") == true || b != 0) {
                et3.setForeground(Color.red);
                //theme.setBackground(Color.red);
            }
            if (Ctel.getText().equals("") == true || c == 0) {
                et4.setForeground(Color.red);
                //specialite.setBackground(Color.red);
            }
            if (CAdresse1.getText().equals("") == true || d != 0) {
                et5.setForeground(Color.red);
                //tel.setBackground(Color.red);
            }

            if (Ccin.getText().equals("") == true || e == 0) {
                et6.setForeground(Color.red);
                //budget.setBackground(Color.red);
            }

            if(CLogin.getText().equals(azerty.getLogin())==true || g!=0 ){

                et5.setForeground(Color.red);
            }
            if (controler.matches() != true) {
                et7.setForeground(Color.red);
                //mail.setBackground(Color.red);
            }

        }
    }//GEN-LAST:event_btn_VmodifActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed

        CNom.setText("");
        CPrenom.setText("");
        CDateN.setText("");
        Ctel.setText("");
        CLogin.setText("");
        Ccin.setText("");
        CMail.setText("");
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        String masque = "^[a-zA-Z]+[a-zA-Z0-9\\._-]*[a-zA-Z0-9]@[a-zA-Z]+" + "[a-zA-Z0-9\\._-]*[a-zA-Z0-9]+\\.[a-zA-Z]{2,4}$";
        Pattern pattern = Pattern.compile(masque);
        Matcher controler = pattern.matcher(CMail.getText());
        String resu = " ";
        if (RbHomme.isSelected()) {
            resu = RbHomme.getText();
        }
        if (RbFemme.isSelected()) {
            resu = RbFemme.getText();
        }
        int j = 0;
        int a = 0;
        int b = 0;
        int c = 0;
        int d = 0;
        int e = 0;
        int f = 0;
        int g = 0;

        try {
            j = Integer.parseInt(CNom.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            a = Integer.parseInt(CPrenom.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            b = Integer.parseInt(CDateN.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            c = Integer.parseInt(Ctel.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            d = Integer.parseInt(CAdresse1.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            g = Integer.parseInt(CLogin.getText());

        } catch (NumberFormatException ex) {
        }

        try {
            e = Integer.parseInt(Ccin.getText());

        } catch (NumberFormatException ex) {
        }
        try {
            f = Integer.parseInt(CMail.getText());

        } catch (NumberFormatException ex) {
        }

        String test = CLogin.getText();
        authentificationDAO aut;
        aut = new authentificationDAO();
        authentification azerty = aut.verifierR(test);

        if (CNom.getText().equals("") == false && j == 0 && CPrenom.getText().equals("") == false && a == 0 && CDateN.getText().equals("") == false && b == 0 && Ctel.getText().equals("") == false && c != 0 && CAdresse1.getText().equals("") == false && d == 0 && Ccin.getText().equals("") == false && e != 0 && controler.matches() == true && g == 0 && CLogin.getText().equals(azerty.getLogin()) == false) {
            RestaurateurDAO resDAO = new RestaurateurDAO();
            Restaurateur res = new Restaurateur();
            authentification au = new authentification();

            au.setLogin(CLogin.getText());
            au.setPassword(cPassword.getText());
            res.setNom(CNom.getText());
            res.setPrenom(CPrenom.getText());
            res.setDate_naissance(CDateN.getText());
            res.setTel(Integer.parseInt(Ctel.getText()));
            res.setAdresse(CLogin.getText());
            res.setSexe(resu);
            res.setCin(Integer.parseInt(Ccin.getText()));
            res.setMail(CMail.getText());
            JOptionPane.showConfirmDialog(this, "voulez vous confirmer votre insertion");
            //  System.out.println(res);
            resDAO.ajouterRestaurateur(res, au);

        } else {
            if (CNom.getText().equals("") == true || j != 0) {
                et1.setForeground(Color.red);
                //nom.setBackground(Color.red);
            }
            if (CPrenom.getText().equals("") == true || a != 0) {
                et2.setForeground(Color.red);
                //adresse.setBackground(Color.red);
            }
            if (CDateN.getText().equals("") == true || b != 0) {
                et3.setForeground(Color.red);
                //theme.setBackground(Color.red);
            }
            if (Ctel.getText().equals("") == true || c == 0) {
                et4.setForeground(Color.red);
                //specialite.setBackground(Color.red);
            }
            if (CAdresse1.getText().equals("") == true || d != 0) {
                et5.setForeground(Color.red);
                //tel.setBackground(Color.red);
            }

            if (Ccin.getText().equals("") == true || e == 0) {
                et6.setForeground(Color.red);
                //budget.setBackground(Color.red);
            }

            if (CLogin.getText().equals(azerty.getLogin()) == true || g != 0) {

                et5.setForeground(Color.red);
            }

            if (controler.matches() != true) {
                et7.setForeground(Color.red);
                //mail.setBackground(Color.red);
            }

        }
    }//GEN-LAST:event_btn_validerActionPerformed

    private void RbHommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbHommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbHommeActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        List<Restaurateur> lis = new RestaurateurDAO().RechercherAllRestaurateurs(jTextField1.getText());
        ModelTableRestaurateurs model1 = new ModelTableRestaurateurs(lis);
        tbLste.setModel(model1);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        if (tbLste.getSelectedRow() != -1) {
            Restaurateur c = new Restaurateur();
            RestaurateurDAO rdao = new RestaurateurDAO();
            c = rdao.findRestaurateurById((Integer) tbLste.getValueAt(tbLste.getSelectedRow(), 10));
            t = (Integer) tbLste.getValueAt(tbLste.getSelectedRow(), 10);

            title.setText("Modifier restaurateur");
            btn_Vmodif.setVisible(true);
            btn_valider.setVisible(false);
            Restaurateur res = new Restaurateur();
            authentificationDAO autd = new authentificationDAO();
            authentification at = autd.rechercheres(t);
            CLogin.setText(at.getLogin());
            cPassword.setText(at.getPassword());
            y=at.getId();
            CNom.setText(c.getNom());
            CPrenom.setText(c.getPrenom());
            CDateN.setText(c.getDate_naissance());
            Ctel.setText(String.valueOf(c.getTel()));
            CAdresse1.setText(c.getAdresse());
            Ccin.setText(String.valueOf(c.getCin()));
            CMail.setText(c.getMail());

            if(c.getSexe().equals("Femme")){

                RbFemme.setSelected(true);
            }
            if(c.getSexe().equals("Homme")){
                RbHomme.setSelected(true);
            }

            //this.setVisible(true);
        } else {
            int d = JOptionPane.OK_CANCEL_OPTION;
            JOptionPane.showConfirmDialog(null, "Vous n'avez pas sélectionnez un restaurateur", "erreur", d);

        }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Voulez vous supprimer le(ou les) restaurateurs selectionnés?", "Warning", dialogButton);

        if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here

            RestaurateurDAO resDAO = new RestaurateurDAO();
            int ids[] = new int[50];
            int j = -1;
            for (int i = 0; i < tbLste.getRowCount(); i++) {
                Boolean b = (Boolean) tbLste.getValueAt(i, 9);
                if (b) {
                    j++;

                    ids[j] = (Integer) tbLste.getValueAt(i, 10);
                }

            }
            while (j != -1) {
                resDAO.deleteRestaurateur(ids[j]);
                j--;
            }
            ModelTableRestaurateurs model = new ModelTableRestaurateurs();
            tbLste.setModel(model);
        }
    }//GEN-LAST:event_btnSuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste_restaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste_restaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste_restaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste_restaurateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste_restaurateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAdresse1;
    private javax.swing.JTextField CDateN;
    private javax.swing.JTextField CLogin;
    private javax.swing.JTextField CMail;
    private javax.swing.JTextField CNom;
    private javax.swing.JTextField CPrenom;
    private javax.swing.JTextField Ccin;
    private javax.swing.JTextField Ctel;
    private javax.swing.JPanel Gestionrestaurateur;
    private javax.swing.JRadioButton RbFemme;
    private javax.swing.JRadioButton RbHomme;
    private javax.swing.JButton btnSupp;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btn_Annuler;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Vmodif;
    private javax.swing.JButton btn_valider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField cPassword;
    private javax.swing.JLabel et1;
    private javax.swing.JLabel et2;
    private javax.swing.JLabel et3;
    private javax.swing.JLabel et4;
    private javax.swing.JLabel et5;
    private javax.swing.JLabel et6;
    private javax.swing.JLabel et7;
    private javax.swing.JLabel et8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlabel15;
    private javax.swing.JTable tbLste;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
